augmentation:
  crop_center_y_offset: 0
  crop_size: 112
  final_size: 112
  flip: false
  scale_aug: 0.0
  trans_aug: 0.0
common:
  auto_denan: true
  base_lr: 0.01
  batch_size: 128
  decoder:
    kwargs:
      alpha: 40.0
      false_alpha: 48.0
      fc_std: 0.001
      m1: 1.15
      m3: 0.0
      margin: 0.22000000000000003
      type: ArcFaceRescale
    type: Decoder
  deterministic: true
  lr_mults:
  - 0.1
  - 0.1
  - 0.1
  lr_steps:
  - 60000
  - 100000
  - 130000
  max_iter: 150000
  model:
    kwargs:
      bn_group_size: 1
      bn_sync_stats: true
      feature_dim: 256
    test:
      output_name: feature
    type: mobilenetv2_modified
  momentum: 0.9
  nesterov: true
  print_freq: 10
  random_seed: 0
  save_interval: 30000
  shuffle_strategy: 1
  warmup_linear_start_lr: 0.01
  warmup_linear_steps: 3000
  warmup_lr: 0.1
  warmup_steps: 3000
  weight_decay: 0.0005
  worker_rank: true
  workers: 3

